name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: prod or np
        options: 
        - np
        - prod

  push:
    branches:
      - main
env:
  app-name: rq

jobs:
  deploy:
    strategy:
      matrix:
        region: [ 'us-east-1']
    environment: ${{ inputs.environment == '' && 'np' || inputs.environment }}
    runs-on: ubuntu-latest

    steps:
    - name: Set environment variable
      id: set-env
      run: echo "ENVIRONMENT=${{ inputs.environment == '' && 'np' || inputs.environment }}" >> $GITHUB_ENV

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
  
    - name: AWS CLI setup
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ matrix.region }}
        
    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
          mask-password: true

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile
        build-args: 
        platforms: linux/amd64
        push: true
        tags: |
          ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ matrix.region }}.amazonaws.com/${{ env.app-name }}-repo:latest
          ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ matrix.region }}.amazonaws.com/${{ env.app-name }}-repo:${{ github.sha }}_${{ github.run_id }}
      
    - name: Register and Update Task Definition
      run: |
        set -ex
        pip install awscli
        aws ecs update-service --cluster ${{ env.app-name }}-cluster --service ${{ env.app-name }}-service --force-new-deployment
